---    
- name: Write hostname
  hosts: routers
  vars:
    ntp_servers: '1.1.1.1'
  tasks:
  - name: write hostname using jinja2
    ansible.builtin.template:
       src: template_global.j2
       dest: "{{ inventory_hostname }}"
