---
- name: Apply the provided configuration
  hosts: routers
  tasks:
  - name: ntp
    cisco.ios.ios_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
    loop:
      - 2.2.2.2
      - 3.3.3.3
  state: replaced