---
- name: Write hostname
  hosts: routers  
  tasks:
  - name: write hostname using jinja2
    ansible.builtin.template:
       src: template_global.j2
       dest: ./config/{{ inventory_hostname }}.txt
