---
- name: base
  hosts: routers

  tasks:
    - name: Gather only the config and default facts
      cisco.ios.ios_facts:
        gather_subset:
          - config

    - name: config facts
      ansible.builtin.debug:
        msg: "{{ansible_net_config}}"

    - name: Assemble configuration
      assemble:
        src: "config/parts/{{inventory_hostname}}"
        dest: "config/{{inventory_hostname}}/compiled.config"
        regexp: "^.*"
      delegate_to: localhost

    - name: update config
      cisco.ios.ios_config:
        src: "config/{{inventory_hostname}}/compiled.config"
    
  roles:
  - ntp
  - syslog