---
  vars:
    ntp_servers: 1.1.1.1'
    
- name: Write hostname
  hosts: routers
  tasks:
  - name: write hostname using jinja2
    ansible.builtin.template:
       src: template_global.j2
       dest: ./configs/{{ inventory_hostname }}_config.txt
