---
- name: Apply the provided configuration
  hosts: routers
  state: merged
  tasks:
  - name: ntp
    cisco.ios.ios_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
    loop: "{{ ntp_servers }}"